// Generates src/styles/theme.css (the colour variables behind src/styles/tokens.ts) and checks
// WCAG contrast for every text/background pairing the components use, in both themes.
// Run: node scripts/theme.mjs        (fails if any pairing is below its AA threshold)
import { writeFileSync } from "node:fs";

const light = {
  brand: { 50: "#EEF6F1", 100: "#D6EBDF", 200: "#ACD6BE", 300: "#79BB96", 400: "#479C70", 500: "#227A52", 600: "#1B6644", 700: "#175439", 800: "#123E2C", 900: "#0C2B1F" },
  gold: { 50: "#FEF8E7", 100: "#FCEEC2", 200: "#F9DF8A", 300: "#F6CF58", 400: "#F4C542", 500: "#E0AC1C", 600: "#A87C0B", 700: "#7C5A08", 800: "#5C4308", 900: "#3A2A05" },
  coral: { 50: "#FEF1EF", 100: "#FDDDD8", 200: "#FAB9B0", 300: "#F6907F", 400: "#F26B5B", 500: "#DE4F3F", 600: "#B83B2D", 700: "#8C2D22", 800: "#621F18", 900: "#3F140F" },
  academic: { 50: "#EEF0FC", 100: "#DADFF8", 200: "#B6BFF1", 500: "#4F5BD5", 600: "#3E47B8", 700: "#2F3690" },
  technical: { 50: "#F4EFFD", 100: "#E6DBFA", 200: "#CDB7F4", 500: "#7C4DDB", 600: "#6639C2", 700: "#512C9C" },
  errand: { 50: "#FEF3EA", 100: "#FCE2CB", 200: "#F8C597", 500: "#E8741C", 600: "#B85A10", 700: "#8F440B" },
  admin: { 50: "#E9F7F6", 100: "#CDEDEA", 200: "#9BDAD4", 500: "#1C9A8F", 600: "#127268", 700: "#0E5A53" },
  info: { 50: "#EEF5FE", 100: "#D9E8FC", 200: "#B4D0F8", 500: "#3B82F6", 600: "#2563EB", 700: "#1D4ED8", 800: "#1E40AF" },
  warning: { 50: "#FFF8E6", 100: "#FEEDC2", 200: "#FDDB8A", 400: "#F8B93A", 500: "#EA9A0C", 600: "#B06A05", 700: "#8A5307", 800: "#6B3F08" },
  danger: { 50: "#FEF1F1", 100: "#FDE0E0", 200: "#FBC2C2", 500: "#E5484D", 600: "#C42B32", 700: "#9E2228" },
  board: "#1F5C45", "board-deep": "#173F31", chalk: "#F6F2E6", "chalk-dust": "#CFDDD3",
  ink: "#1D2621", muted: "#57615A", faint: "#98A19A",
  line: "#E7DFCC", "line-strong": "#D3C7AA", sunken: "#F4EEDF", canvas: "#FBF6EA", surface: "#FFFDF8",
  shadow: "#4A3A18",
};

// Dark is the board itself. Scales flip: 50 is the deepest tint, 700 the lightest text.
const dark = {
  brand: { 50: "#16332A", 100: "#1C4234", 200: "#285A46", 300: "#3A785D", 400: "#529777", 500: "#2A7F56", 600: "#246F4B", 700: "#9DD9B8", 800: "#C0EBD2", 900: "#E2F5EA" },
  gold: { 50: "#352A0E", 100: "#453611", 200: "#6B5314", 300: "#9C7A1A", 400: "#E0B53A", 500: "#F4C542", 600: "#F6CF58", 700: "#F9DF8A", 800: "#FCEEC2", 900: "#FEF8E7" },
  coral: { 50: "#3A1B17", 100: "#4D221C", 200: "#733127", 300: "#A5443A", 400: "#E36353", 500: "#F26B5B", 600: "#F6907F", 700: "#FAB9B0", 800: "#FDDDD8", 900: "#FEF1EF" },
  academic: { 50: "#1E2344", 100: "#262C58", 200: "#353F82", 500: "#8C95EC", 600: "#A7AEF1", 700: "#C6CBF6" },
  technical: { 50: "#2A1F47", 100: "#35285A", 200: "#4B3886", 500: "#AE8CF0", 600: "#C2A8F4", 700: "#D9C9F8" },
  errand: { 50: "#3A2413", 100: "#4A2E16", 200: "#6E431C", 500: "#F29A52", 600: "#F6B47D", 700: "#F9CDA7" },
  admin: { 50: "#12332F", 100: "#16413C", 200: "#1F5E57", 500: "#4FC3B7", 600: "#7DD4CB", 700: "#A9E3DD" },
  info: { 50: "#172A45", 100: "#1D3558", 200: "#284B7D", 500: "#6FA5F8", 600: "#93BCFA", 700: "#B6D2FB", 800: "#D3E4FD" },
  warning: { 50: "#392A0C", 100: "#48350F", 200: "#6D5015", 400: "#E3A93A", 500: "#F4BE55", 600: "#F7CD7A", 700: "#F9DCA0", 800: "#FCEBC9" },
  danger: { 50: "#3D1A1C", 100: "#4E2023", 200: "#763033", 500: "#F07A7E", 600: "#C9373E", 700: "#F7B1B3" },
  board: "#1F5C45", "board-deep": "#133528", chalk: "#F4F0E3", "chalk-dust": "#C6D6CB",
  ink: "#EDEADF", muted: "#A9B4AC", faint: "#728077",
  line: "#2B3C33", "line-strong": "#3B5046", sunken: "#1F2D26", canvas: "#131C18", surface: "#18241E",
  shadow: "#000000",
};

const rgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
const flat = (theme) =>
  Object.entries(theme).flatMap(([k, val]) => (typeof val === "string" ? [[k, val]] : Object.entries(val).map(([s, hex]) => [`${k}-${s}`, hex])));
const vars = (theme, indent) =>
  flat(theme).map(([k, hex]) => `${indent}--c-${k}: ${rgb(hex).join(" ")};`).join("\n").replace("--c-shadow", "--shadow");

const css = `/* Generated by scripts/theme.mjs. Edit the palettes there, not here. */
:root {
  color-scheme: light;
${vars(light, "  ")}
}
@media (prefers-color-scheme: dark) {
  :root {
    color-scheme: dark;
${vars(dark, "    ")}
  }
}
`;
writeFileSync("src/styles/theme.css", css);

// --- WCAG AA checks for the pairings in use ---------------------------------------------
const lum = (hex) => {
  const c = rgb(hex).map((x) => { x /= 255; return x <= 0.03928 ? x / 12.92 : ((x + 0.055) / 1.055) ** 2.4; });
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
};
const ratio = (a, b) => { const [x, y] = [lum(a), lum(b)].sort((m, n) => n - m); return (x + 0.05) / (y + 0.05); };
const get = (t, key) => Object.fromEntries(flat(t))[key];
const pairs = [
  // [text, background, minimum]
  ["ink", "canvas", 4.5], ["ink", "surface", 4.5], ["muted", "canvas", 4.5], ["muted", "surface", 4.5], ["muted", "sunken", 4.5],
  ["chalk", "board", 4.5], ["chalk-dust", "board", 4.5],
  ...["brand", "gold", "coral", "academic", "technical", "errand", "admin", "info", "warning", "danger"].map((s) => [`${s}-700`, `${s}-50`, 4.5]),
  ...["academic", "technical", "errand", "admin"].map((s) => [`${s}-700`, "surface", 4.5]),
  ["brand-700", "canvas", 4.5], ["brand-700", "surface", 4.5], ["danger-700", "surface", 4.5], ["warning-800", "warning-50", 4.5],
];
const onFill = [["#FFFFFF", "brand-500"], ["#FFFFFF", "brand-600"], ["#FFFFFF", "danger-600"], ["#FFFFFF", "board"]];
let failed = 0;
for (const [name, t] of [["light", light], ["dark", dark]]) {
  for (const [fg, bg, min] of pairs) {
    const r = ratio(get(t, fg), get(t, bg));
    if (r < min) { failed++; console.log(`FAIL ${name}: ${fg} on ${bg} = ${r.toFixed(2)} (needs ${min})`); }
  }
  for (const [fg, bg] of onFill) {
    const r = ratio(fg, get(t, bg));
    if (r < 4.5) { failed++; console.log(`FAIL ${name}: white on ${bg} = ${r.toFixed(2)} (needs 4.5)`); }
  }
}
console.log(failed ? `${failed} contrast failures` : "All pairings meet WCAG AA in both themes.");
process.exit(failed ? 1 : 0);
